-- Data context: CUSTOMERUNIFIEDINFO (current-customer filter). Interop active but no SKU.
SELECT
  COMPANY_SFDC_ID,
  COMPANY_NAME,
  SEGMENT,
  USAGE_DEPLOYMENT_OPTION,
  ARR_EUR
FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO
WHERE MONTH_DT = (SELECT MAX(MONTH_DT) FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO)
  AND IS_CURRENT_CUSTOMER AND IS_CUSTOMER_POLICY
  AND IS_INTEROPERABILITY = TRUE
  AND HAS_SKU_INTEROPERABILITY = FALSE
ORDER BY ARR_EUR DESC NULLS LAST
