SELECT
  TO_DATE(CAST(DATE_ID AS VARCHAR), 'YYYYMMDD') AS MONTH_START,
  COUNT(DISTINCT CASE WHEN IS_INTEROPERABILITY = TRUE THEN COMPANY_ID END) AS INTEROP_CUSTOMERS,
  COUNT(DISTINCT CASE WHEN HAS_SKU_INTEROPERABILITY = TRUE THEN COMPANY_ID END) AS SKU_INTEROP_CUSTOMERS,
  COUNT(DISTINCT COMPANY_ID) AS TOTAL_CUSTOMERS,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN IS_INTEROPERABILITY = TRUE THEN COMPANY_ID END) / NULLIF(COUNT(DISTINCT COMPANY_ID), 0), 2) AS ADOPTION_PCT
FROM CANONICAL.CUSTOMERSUCCESS.MONTHLYCOMPANYPRODUCTEDITIONCATEGORY
WHERE DATE_ID >= REPLACE(CAST(DATEADD('month', -12, CURRENT_DATE) AS VARCHAR(10)), '-', '')
GROUP BY 1
ORDER BY 1 DESC
