SELECT
  PRODUCT_FAMILY,
  PRODUCT_CATEGORY,
  COUNT(DISTINCT COMPANY_ID) AS TOTAL_CUSTOMERS,
  COUNT(DISTINCT CASE WHEN IS_INTEROPERABILITY = TRUE THEN COMPANY_ID END) AS INTEROP_ACTIVE,
  COUNT(DISTINCT CASE WHEN HAS_SKU_INTEROPERABILITY = TRUE THEN COMPANY_ID END) AS HAS_SKU_INTEROP
FROM CANONICAL.CUSTOMERSUCCESS.MONTHLYCOMPANYPRODUCTEDITIONCATEGORY
WHERE DATE_ID = (SELECT MAX(DATE_ID) FROM CANONICAL.CUSTOMERSUCCESS.MONTHLYCOMPANYPRODUCTEDITIONCATEGORY)
GROUP BY 1, 2
ORDER BY INTEROP_ACTIVE DESC
