SELECT
  INFRA_ARCH_TYPE,
  PRODUCT_FAMILY,
  COUNT(DISTINCT COMPANY_SFDC_ID) AS COMPANIES,
  COUNT(DISTINCT CASE WHEN IS_INTEROPERABILITY = TRUE THEN COMPANY_SFDC_ID END) AS INTEROP_COMPANIES,
  COUNT(DISTINCT CASE WHEN HAS_SKU_INTEROPERABILITY = TRUE THEN COMPANY_SFDC_ID END) AS SKU_INTEROP
FROM CANONICAL.CUSTOMERSUCCESS.MONTHLYCOMPANYINFRAPRODUCTEDITIONCATEGORY
WHERE USAGEDATE = (SELECT MAX(USAGEDATE) FROM CANONICAL.CUSTOMERSUCCESS.MONTHLYCOMPANYINFRAPRODUCTEDITIONCATEGORY)
GROUP BY 1, 2
ORDER BY INTEROP_COMPANIES DESC
