SELECT
  DATE_TRUNC('month', DATE) AS MONTH,
  COUNT(DISTINCT INFRASTRUCTURE_ID) AS ACTIVE_INFRA,
  SUM(INTEROPERABILITY_AGGREGATED_EXECUTIONS_PROD_SUM) AS PROD_EXECUTIONS,
  SUM(INTEROPERABILITY_AGGREGATED_EXECUTIONS_DEV_SUM) AS DEV_EXECUTIONS,
  SUM(INTEROPERABILITY_AGGREGATED_EXECUTIONS_NONPROD_SUM) AS NONPROD_EXECUTIONS,
  SUM(INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_PROD_SUM) AS PROD_AO_USAGE
FROM CANONICAL.CUSTOMERSUCCESS.PLATFORMUTILIZATIONDAILYINFRASTRUCTUREAGG
WHERE DATE >= DATEADD('month', -7, CURRENT_DATE)
  AND (INTEROPERABILITY_AGGREGATED_EXECUTIONS_PROD_SUM > 0
       OR INTEROPERABILITY_AGGREGATED_EXECUTIONS_DEV_SUM > 0
       OR INTEROPERABILITY_AGGREGATED_EXECUTIONS_NONPROD_SUM > 0)
GROUP BY 1
ORDER BY 1 DESC
