SELECT
  TO_DATE(CAST(DATE_ID AS VARCHAR), 'YYYYMMDD') AS REPORT_MONTH,
  COUNT(DISTINCT INFRASTRUCTURE_ID) AS ACTIVE_INFRA,
  SUM(INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_PROD_LASTWEEK) AS PROD_AO_LAST_WEEK,
  SUM(INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_DEV_LASTWEEK) AS DEV_AO_LAST_WEEK,
  SUM(INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_PROD_MAXWEEK) AS PROD_AO_MAX_WEEK,
  SUM(INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_DEV_MAXWEEK) AS DEV_AO_MAX_WEEK
FROM CANONICAL.CUSTOMERSUCCESS.PLATFORMUTILIZATIONMONTHLYINFRASTRUCTUREAGG_TOTAL
WHERE DATE_ID >= REPLACE(CAST(DATEADD('month', -7, CURRENT_DATE) AS VARCHAR(10)), '-', '')
  AND (INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_PROD_LASTWEEK > 0
       OR INTEROPERABILITY_AGGREGATED_USAGE_AO_VALUE_DEV_LASTWEEK > 0)
GROUP BY 1
ORDER BY 1 DESC
