SELECT
  IS_INTEROPERABILITY,
  HAS_SKU_INTEROPERABILITY,
  COUNT(*) AS COMPANY_COUNT
FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO
WHERE IS_LAST_MONTH_REPORTED
  AND IS_CURRENT_CUSTOMER
  AND IS_CUSTOMER_POLICY
GROUP BY 1, 2
ORDER BY 1, 2
