SELECT
  IS_INTEROPERABILITY,
  HAS_SKU_INTEROPERABILITY,
  COUNT(*) AS COMPANY_COUNT
FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO
WHERE MONTH_DT = (SELECT MAX(MONTH_DT) FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO)
  AND IS_CURRENT_CUSTOMER
  AND IS_CUSTOMER_POLICY
GROUP BY 1, 2
ORDER BY 1, 2
