-- Data context: CUSTOMERUNIFIEDINFO (current-customer filter), ODCAGENT (latest DATE_MONTH).
WITH customer_counts AS (
  SELECT USAGE_DEPLOYMENT_OPTION, COUNT(DISTINCT COMPANY_SFDC_ID) AS total_customers
  FROM CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO
  WHERE USAGE_DEPLOYMENT_OPTION IN ('O11', 'ODC', 'O11/ODC')
    AND IS_LAST_MONTH_REPORTED
    AND IS_CURRENT_CUSTOMER AND IS_CUSTOMER_POLICY
  GROUP BY 1
),
agent_stats AS (
  SELECT c.USAGE_DEPLOYMENT_OPTION,
         COUNT(DISTINCT a.COMPANY_SFDC_ID) AS customers_with_agents,
         SUM(a.N_AGENTS)                   AS total_agents,
         SUM(a.N_EXECUTIONS)               AS total_executions
  FROM CANONICAL.CUSTOMERSUCCESS.ODCAGENT a
  INNER JOIN CANONICAL.CUSTOMERSUCCESS.CUSTOMERUNIFIEDINFO c
    ON a.COMPANY_SFDC_ID = c.COMPANY_SFDC_ID
  WHERE c.USAGE_DEPLOYMENT_OPTION IN ('O11', 'ODC', 'O11/ODC')
    AND c.IS_LAST_MONTH_REPORTED
    AND c.IS_CURRENT_CUSTOMER AND c.IS_CUSTOMER_POLICY
    AND a.DATE_MONTH = (SELECT MAX(DATE_MONTH) FROM CANONICAL.CUSTOMERSUCCESS.ODCAGENT)
  GROUP BY 1
)
SELECT
  cc.USAGE_DEPLOYMENT_OPTION,
  cc.total_customers,
  COALESCE(ag.customers_with_agents, 0) AS customers_with_agents,
  ROUND(COALESCE(ag.customers_with_agents, 0)::FLOAT / NULLIF(cc.total_customers, 0)::FLOAT * 100, 1) AS adoption_rate_pct,
  COALESCE(ag.total_agents, 0)     AS total_agents,
  COALESCE(ag.total_executions, 0) AS total_executions
FROM customer_counts cc
LEFT JOIN agent_stats ag ON cc.USAGE_DEPLOYMENT_OPTION = ag.USAGE_DEPLOYMENT_OPTION
ORDER BY cc.USAGE_DEPLOYMENT_OPTION
